name: matriz-dev-project
services:
  only_db:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432:5432'
    env_file:
      - .env
    labels:
      org.springframework.boot.service-connection: postgres
