app:
  jwt:
    secret: ${SEC_SECRET}
    expiration-ms: 900000
    refresh-expiration-ms: 604800000
  frontend:
    url: ${FRONTEND_URL}
  cookie:
    security: ${COOKIE_SECURITY}
    domain: ${COOKIE_DOMAIN}
spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile
            - openid
cloud:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    endpoint: ${R2_ENDPOINT}
    bucket-name: ${R2_BUCKET_NAME}
    public-url: ${R2_PUBLIC_URL}